'use strict';

function dshShellHtml(options) {
  const harnessUrl = JSON.stringify(String(options && options.harnessUrl || 'http://127.0.0.1:3080/'));
  return `<!doctype html>
<html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>DSH Core</title><style>
:root{font-family:Inter,"Segoe UI",system-ui,sans-serif;color:#202124;background:#fff}*{box-sizing:border-box}body{margin:0;overflow:hidden}
header{height:54px;display:flex;align-items:center;gap:12px;padding:0 16px;border-bottom:1px solid #e7e9ee;background:#fff;transition:height .18s ease,transform .18s ease}
.brand{font-weight:700}.dot{width:9px;height:9px;border-radius:50%;background:#23a55a}.muted{color:#737987;font-size:13px}.spacer{flex:1}
button,select{border:1px solid #d9dde7;background:#fff;border-radius:9px;padding:8px 11px;font:inherit}button{cursor:pointer}button:disabled{cursor:wait;opacity:.62}button.primary{background:#3567f0;color:#fff;border-color:#3567f0}button.danger{color:#b42318}
main{position:relative;height:calc(100vh - 54px);transition:height .18s ease}iframe{border:0;width:100%;height:100%;background:#fff}
body.toolbar-collapsed header{height:0;transform:translateY(-54px);overflow:hidden;border:0}body.toolbar-collapsed main{height:100vh}.toolbar-tab{display:none;position:fixed;z-index:8;top:8px;left:50%;transform:translateX(-50%);padding:5px 14px;border-radius:999px;background:#fff;box-shadow:0 2px 12px #1d243329}body.toolbar-collapsed .toolbar-tab{display:block}
.drawer{position:absolute;z-index:6;right:16px;top:16px;width:min(760px,55vw);height:min(760px,calc(100% - 32px));min-width:360px;min-height:260px;max-width:calc(100% - 16px);max-height:calc(100% - 16px);background:#fff;border:1px solid #dfe2ea;border-radius:12px;box-shadow:0 14px 40px #1d243338;display:none;grid-template-rows:auto minmax(0,1fr);overflow:hidden}.drawer.open{display:grid}
.drawer.dragging,.drawer.resizing{user-select:none}.drawer.dragging iframe,.drawer.resizing iframe{pointer-events:none}.drawer-head{display:flex;align-items:center;gap:10px;padding:10px 12px;border-bottom:1px solid #e7e9ee;cursor:move;touch-action:none}.drawer-head button{cursor:pointer}.drawer iframe{background:#111}.pill{padding:4px 8px;border-radius:99px;background:#eef2ff;color:#3557c7;font-size:12px}.resize-handle{position:absolute;right:0;bottom:0;width:22px;height:22px;cursor:nwse-resize;touch-action:none;background:linear-gradient(135deg,transparent 48%,#aeb5c4 49%,#aeb5c4 58%,transparent 59%,transparent 68%,#7d8799 69%,#7d8799 78%,transparent 79%)}
@media(max-width:800px){.drawer{width:100%}.muted.wide{display:none}header{padding:0 9px;gap:7px}button,select{padding:7px}}
</style></head><body>
<header><span class="dot"></span><span class="brand">DSH Core</span><span id="state" class="muted">正在读取账号…</span><span class="spacer"></span><select id="provider"><option value="deepseek">DeepSeek</option><option value="qwen">Qianwen 生图</option></select><select id="accounts" title="Provider 账号"></select><button id="add">新账号</button><button id="view">查看网页</button><button id="login" class="primary">登录 / 切换</button><button id="reload" title="只重新加载当前 DSH 页面，不重启进程">刷新页面</button><button id="restart" title="停止并重新启动 DSH 进程">重启 DSH</button><button id="collapse" title="折叠顶部工具栏">折叠</button></header>
<button id="expand" class="toolbar-tab" title="展开 DSH Core 工具栏">展开 DSH Core</button>
<main><iframe id="dsh" title="DeepSeek Harness" allow="clipboard-read; clipboard-write"></iframe><aside id="drawer" class="drawer"><div id="drawerHead" class="drawer-head"><b id="drawerTitle">Provider 网页</b><span class="pill">远端 Chromium</span><span class="muted wide">拖动标题栏移动，拖动右下角缩放</span><span class="spacer"></span><button id="resetWindow" title="恢复默认大小与位置">还原</button><button id="close">收起</button></div><iframe id="loginFrame" title="Provider Browser"></iframe><div id="resizeHandle" class="resize-handle" title="拖动缩放"></div></aside></main>
<script>
let harnessUrl=${harnessUrl};
const S={provider:'deepseek',accounts:null,loginStarted:false};
const $=id=>document.getElementById(id);
async function api(path,opt={}){const r=await fetch(path,{...opt,headers:{'Content-Type':'application/json',...(opt.headers||{})}});const p=await r.json();if(!r.ok)throw new Error(p.error&&p.error.message||r.statusText);return p}
function active(){return S.accounts&&S.accounts.data.find(x=>x.id===S.accounts.active_account_id)}
function providerLabel(){return S.provider==='qwen'?'Qianwen 生图':'DeepSeek'}
function showLogin(){ $('drawerTitle').textContent=providerLabel()+' 网页';$('drawer').classList.add('open');if(!$('loginFrame').src)$('loginFrame').src='http://127.0.0.1:6080/vnc.html?autoconnect=1&resize=scale'; }
async function refresh(){try{const p=await api('/api/dsh-shell/status?provider='+encodeURIComponent(S.provider));S.accounts=p.accounts;const current=active();$('accounts').innerHTML=p.accounts.data.map(x=>'<option value="'+x.id+'">'+(x.name||x.id)+'</option>').join('');$('accounts').value=p.accounts.active_account_id;$('state').textContent=current&&current.last_login_at?providerLabel()+' 已登录':providerLabel()+' 尚未登录';if(current&&!current.last_login_at&&!S.loginStarted){S.loginStarted=true;await beginLogin(true)}}catch(e){$('state').textContent=e.message}}
async function beginLogin(auto){showLogin();$('state').textContent='等待 '+providerLabel()+' 登录…';try{await api('/api/dsh-shell/browser',{method:'POST',body:JSON.stringify({provider:S.provider,visible:true,account_id:$('accounts').value||'default'})});if(!auto)S.loginStarted=true}catch(e){$('state').textContent=e.message}}
async function viewProvider(){showLogin();$('state').textContent='正在打开 '+providerLabel()+' 网页…';try{await api('/api/dsh-shell/browser',{method:'POST',body:JSON.stringify({provider:S.provider,visible:true,account_id:$('accounts').value||'default'})});$('state').textContent=providerLabel()+' 网页已切换为可见模式'}catch(e){$('state').textContent=e.message}}
$('login').onclick=()=>beginLogin(false);$('view').onclick=viewProvider;$('close').onclick=()=>{$('drawer').classList.remove('open')};$('reload').onclick=()=>{$('dsh').src=harnessUrl};
$('restart').onclick=async()=>{const button=$('restart');button.disabled=true;$('state').textContent='正在重启 DSH…';try{const status=await api('/api/dsh-shell/restart',{method:'POST',body:'{}'});const next=String(status.url||harnessUrl);harnessUrl=next.endsWith('/')?next:next+'/';$('dsh').src=harnessUrl;$('state').textContent='DSH 已重启'}catch(e){$('state').textContent='DSH 重启失败：'+e.message}finally{button.disabled=false}};
function setToolbarCollapsed(collapsed){document.body.classList.toggle('toolbar-collapsed',collapsed);try{localStorage.setItem('dsh-core-toolbar-collapsed',collapsed?'1':'0')}catch(_){}}
$('collapse').onclick=()=>setToolbarCollapsed(true);$('expand').onclick=()=>setToolbarCollapsed(false);try{setToolbarCollapsed(localStorage.getItem('dsh-core-toolbar-collapsed')==='1')}catch(_){}
function resetProviderWindow(){const drawer=$('drawer');drawer.style.left='';drawer.style.top='16px';drawer.style.right='16px';drawer.style.width='min(760px, 55vw)';drawer.style.height='min(760px, calc(100% - 32px))'}
$('resetWindow').onclick=(event)=>{event.stopPropagation();resetProviderWindow()};
function startWindowGesture(event,mode){if(event.button!==0)return;if(mode==='move'&&event.target.closest('button,select'))return;const drawer=$('drawer'),main=$('drawer').parentElement,rect=drawer.getBoundingClientRect(),bounds=main.getBoundingClientRect();event.preventDefault();drawer.style.left=(rect.left-bounds.left)+'px';drawer.style.top=(rect.top-bounds.top)+'px';drawer.style.right='auto';drawer.style.width=rect.width+'px';drawer.style.height=rect.height+'px';drawer.classList.add(mode==='move'?'dragging':'resizing');const sx=event.clientX,sy=event.clientY,startLeft=rect.left-bounds.left,startTop=rect.top-bounds.top,startWidth=rect.width,startHeight=rect.height;const move=e=>{if(mode==='move'){drawer.style.left=Math.max(0,Math.min(bounds.width-startWidth,e.clientX-sx+startLeft))+'px';drawer.style.top=Math.max(0,Math.min(bounds.height-startHeight,e.clientY-sy+startTop))+'px'}else{drawer.style.width=Math.max(360,Math.min(bounds.width-startLeft,e.clientX-sx+startWidth))+'px';drawer.style.height=Math.max(260,Math.min(bounds.height-startTop,e.clientY-sy+startHeight))+'px'}};const end=()=>{drawer.classList.remove('dragging','resizing');window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',end);window.removeEventListener('pointercancel',end)};window.addEventListener('pointermove',move);window.addEventListener('pointerup',end);window.addEventListener('pointercancel',end)}
$('drawerHead').addEventListener('pointerdown',event=>startWindowGesture(event,'move'));$('resizeHandle').addEventListener('pointerdown',event=>startWindowGesture(event,'resize'));
$('provider').onchange=async()=>{S.provider=$('provider').value;S.accounts=null;S.loginStarted=false;await refresh()};
$('accounts').onchange=async()=>{await api('/api/dsh-shell/select',{method:'POST',body:JSON.stringify({provider:S.provider,account_id:$('accounts').value})});S.loginStarted=false;await refresh()};
$('add').onclick=async()=>{const name=prompt('新账号名称');if(!name||!name.trim())return;const p=await api('/api/dsh-shell/accounts',{method:'POST',body:JSON.stringify({provider:S.provider,name:name.trim()})});await api('/api/dsh-shell/select',{method:'POST',body:JSON.stringify({provider:S.provider,account_id:p.id})});S.loginStarted=false;await refresh()};
$('dsh').src=harnessUrl;refresh();setInterval(async()=>{const before=active()&&active().last_login_at;await refresh();const after=active()&&active().last_login_at;if(!before&&after){$('drawer').classList.remove('open');$('dsh').src=harnessUrl}},2000);
</script></body></html>`;
}

module.exports = { dshShellHtml };
